# Generated by Django 6.0.2 on 2026-09-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0047_merchantprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storefrontbanner",
            options={"ordering": ["placement", "position", "id"]},
        ),
        migrations.RemoveIndex(
            model_name="storefrontbanner",
            name="api_storefr_store_i_254068_idx",
        ),
        migrations.RemoveIndex(
            model_name="storefrontbanner",
            name="api_storefr_store_i_80c614_idx",
        ),
        migrations.AddField(
            model_name="storefrontbanner",
            name="image_url_mobile",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="storefrontbanner",
            name="placement",
            field=models.CharField(
                choices=[
                    ("hero", "Banner principal"),
                    ("promotion", "Banner promocional"),
                ],
                db_index=True,
                default="promotion",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="storefrontbanner",
            index=models.Index(
                fields=["store", "placement", "position"],
                name="api_storefr_store_i_499bd5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="storefrontbanner",
            index=models.Index(
                fields=["store", "placement", "is_active", "starts_at", "ends_at"],
                name="api_storefr_store_i_0de1bf_idx",
            ),
        ),
    ]
